### ISSUE TITLE
[Bug] Black texture on Sprite and Armor

### ISSUE THREAD

**Issue by drakray** [Daveyx0/MultiMob#1]
![2018-12-17_13 09 57](https://user-images.githubusercontent.com/4303126/50124874-7a01bd00-0234-11e9-9240-6dba3c682eaf.png)

I'll post armor shot soon(they are not always black, unlike sprite it seems)

Might be a BoP compat glitch, or maybe something to do with JEID?

**Comment by Daveyx0** [comment]
Did these naturally spawn? Weird, will have to check.

**Comment by drakray** [comment]
Yes, naturally AND eggSpawned
More spawned have colored eyes/leaf, others are totally black

**Comment by lisosaurus** [comment]
I'm getting the same issue with vanilla textures.

**Comment by drakray** [comment]
Could it be caused by other mod like FoamFix, or other "coremods"?

**Comment by Daveyx0** [comment]
It works without my personal modpack; then when I install the other mods, the sprites/chameleons go black. It doesnt appear to be FoamFix; but there is definitely some mod doing this.

**Comment by Daveyx0** [comment]
Ok it's actually CTM... they change the getExtendedBlockState function for what I can tell... sigh...

**Comment by Daveyx0** [comment]
Found a workaround that will be available in the next version \o/
