### ISSUE TITLE
Zombies spawning nonstop in the Nether (1.0.5)

### ISSUE THREAD

**Issue by Marlax0** [Daveyx0/MultiMob#16]
I'm using the latest version of Multi Mob, with the config reset, and no manual edits.
[Forge 1.12.2-14.23.5.2808]

Zombies start to spawn as soon as I enter the Nether.
They infinitely spawn until they hit the mob limit, it seems.
It doesn't happen in the Overworld or the End. I haven't tested any mod-added dimensions, though.

I'm using a lot of mods, but it definitely stops happening when I remove Multi Mob.
[Mod List](https://paste.dimdev.org/ipitixuped.md)

Edit: I tested with Multi Mob enabled and Primitive Mobs disabled and it still happens.

**Comment by Daveyx0** [comment]
Wait with a config reset? That should be impossible. Are you sure? (Fully delete the multimob folder to reset properly)

**Comment by Marlax0** [comment]
Ugh... Looks like it's a mod conflict.
I tested with just Multi Mob installed and the problem doesn't happen.
I have no idea what could be conflicting, but I'll keep looking.

**Comment by Daveyx0** [comment]
Let me know if you find anything. Maybe I can solve it.

**Comment by Marlax0** [comment]
...The bug stopped happening, and I have no idea why.
I thought I was onto something when disabling NetherEx finally made the zombies stop spawning.
But couldn't reproduce the bug at all in a clean test instance with just LibEx, NetherEx, and Multi Mob.
I put NetherEx back in my pack, along with Multi Mob and all the other mods... The bug stayed gone.
My pack is basically identical to how it was when I started this issue, except now the bug is gone.
I've tried deleting the NetherEx and Multi Mob configs to reset them, nothing will reactivate this bug.
I even restored a backup of the original configs, nothing.
I don't know what to say. Minecraft and Forge are very mysterious.

I did manage to take a [screenshot](https://dl.dropboxusercontent.com/s/6nycp8lxkytuj1r/2019-01-31_22.33.07.png) of the bug while it was happening.

**Comment by Daveyx0** [comment]
Glorious... maybe the config never really properly reset or something, maybe it was bugged out. Anyway good to see this being "solved". If anyone else has this issue; feel free to re-open this.

**Comment by drakray** [comment]
I got that also, sadly it seems there is no easy way to fix, so i'll try flushing some config too

**Comment by drakray** [comment]
I think I found something: in config/NetherEx/Biomes/[mods]/[biomes].json, there is a LOT of entry for `"creatureType": "multimob_XXXX",` that shouldn't be there. Might have to reset them all, and reenter my modification

**Comment by Daveyx0** [comment]
Had this issue as well recently. Possibly due to an older MultiMob version. removing the minecraft:zombie entries from NetherEx fixed it for me.

**Comment by drakray** [comment]
Yeah, I reset my NetherEx config altogether after updateing Multimobs, fixed the problem
