### ISSUE TITLE
Excessive spawning of "multimob.dummy"

### ISSUE THREAD

**Issue by kaylee-kiako** [Daveyx0/MultiMob#21]
I'm using the following setup:
- Minecraft; 1.12.2
- Forge; 14.23.5.2811
- MultiMob Core; 1.0.5
- Primitive Mobs; 1.2.3a
- [120+ more mods, though I haven't noticed this issue since my last config change/10 mods added]
- MultiMob config found at [pastebin](https://pastebin.com/q0Y03Yya)

In my current world,
- Difficulty is Normal
- Spawning occurs only at night

I'm having a strange issue where numerous MultiMob dummies (identified via /kill @e[type=!Player] and /summon multimob.dummy) are spawning at night, as seen uploaded here on [imgur](https://imgur.com/lRXdkX4). This may be an issue with how I set up Multimob's config, and if that is the case, all I really need is to know how to fix it.

**Comment by kaylee-kiako** [comment]
Seems to be an issue with what I changed in the config, resetting the config fixed it.

**Comment by Kasia1403** [comment]
What is the command to kill all multimob:dummy ?
