### ISSUE TITLE
Issue with Voidaic Arcana?

### ISSUE THREAD

**Issue by drakray** [Daveyx0/MultiMob#22]
https://pastebin.com/KtPT7GU4

Context: Started a new single player world, Creative, Default Gen, teleported to 0,0, down-digged to Bedrock, broke into void, world crashed, but not MC, just got kicked from the SP game.
This was to test if my inability to go into VoidaicArcana Void Dim was caused by BoP, as I got no crash/error, I just passed directly to the Nether ([see comment thread](https://minecraft.curseforge.com/projects/voidaic-arcania?comment=61))
This time I got this big MultiMobs/PrimitiveMobs crash thing, any idea why?

EDIT: I haven't got this with BoP WorldGen, neither in SP nor MP, haven't tested Default Gen MP though, just SP

**Comment by Daveyx0** [comment]
This appears to be more of a Primitive Mobs crash. The assert references an old server packet message that I dont even use any more so it will be removed for the **next version**. That will likely fix this.

I can enter Voidaic Arcana without issues myself.
