### ISSUE TITLE
When ever I load the game, it crashes due to this issue with Multimod.

### ISSUE THREAD

**Issue by Israphelite** [Daveyx0/MultiMob#6]
I tried to compile this neatly into a pastebin. I know it's caused by multimods, but why?

Link: https://justpaste.it/5rez5

**Comment by Daveyx0** [comment]
Hmm not sure actually, it works with 320 mods here; could be that your forge version is too old? I use the current recommended build to build my mods.

**Comment by Daveyx0** [comment]
Really strange. Do you also get this on a clean install? Going to need some help with this one :/ sorry. Is it on a server?

**Comment by Sninctbur** [comment]
It appears to be a mod compatibility issue, as the game runs normally again when I remove all of my other mods. Looks like I have some singling out to do oh joy

**Comment by Daveyx0** [comment]
Sorry :( Im curious which mod though...

**Comment by Sninctbur** [comment]
Don't sweat it! I've made mods for other games and I know how difficult it can be to fix the simplest of errors. If you want to help, there is a list of the mods I have installed about halfway through the crash report.

**Comment by Sninctbur** [comment]
Update: I found the problem child - it's Optifine.

**Comment by Daveyx0** [comment]
I mean; a specific version of Optifine then? Or the Randomobs option maybe? I use Optifine just fine. hmmst Thanks for checking though

**Comment by Sninctbur** [comment]
Updating Optifine fixed the crash. Thank you for the suggestion!

**Comment by Daveyx0** [comment]
Great! I should probably mention this on the page then. Thanks for checking!

**Comment by Abbetancourt** [comment]
Hey, it worked for me too @Sninctbur thanks! - I kept crashing until I updated Optifine to it latest version available for 12.2.2. I'd recommend putting it on the mod page 😃

**Comment by ghost** [comment]
I had the same crash but I updated to OptiFine_1.12.2_HD_U_E3 and it worked :)
