### ISSUE TITLE
Crashing at startup

### ISSUE THREAD

**Issue by Thesmartone7** [Daveyx0/MultiMob#7]
so it crashes before i can get in-game, and i know it is multimod. might have something to do with the fact that i have a lot of mods, or that my forge version is ...2772. and yes i have the most recent version of optifine for minecraft 1.12 installed and in use, here is the crash report and such link: https://justpaste.it/4jw4p

**Comment by Daveyx0** [comment]
Really strange. I hope it isnt forge. Could you reset your config for multimob to be sure?

**Comment by Thesmartone7** [comment]
with it in my mod folder i cant get in game to reset anything...unless you're talking about some sort of config that i have never seen before, crashes the second forge tries to load it

**Comment by Dawnflare** [comment]
I have encountered the same issue, but only when optifine is installed. other than that, its works great. i hope this helps narrow down the issue so we could find the solution

**Comment by Thesmartone7** [comment]
then its probably related to why ever the most recent optifine, or no optifine, is required...maybe its an issue that should be brought to the attention of the deves of opti?

**Comment by Daveyx0** [comment]
Possibly; I'm generally confused why Optifine changed spawn code; but I cannot be bothered to check it in detail :P

**Comment by xinwolfthorn** [comment]
I have pretty much the same crash and works just fine when i remove optifine..

**Comment by Daveyx0** [comment]
Closing this with reference to above comments seeing as the essential issue is fixed. Im running the mod fine with Optifine... likely that only the more recent versions work.
