### ISSUE TITLE
Game freeze when entering Nether

### ISSUE THREAD

**Issue by Romegon** [Daveyx0/MultiMob#8]
When you enter the nether complete world is black. When you try to move the Server is shutting down. The log says the moltimob lib has some critical actions going on

**Comment by Daveyx0** [comment]
Never seen this and I have 320 mods running. Would need to have a crash report and/or logs in order to get more info. Thanks!

**Comment by Daveyx0** [comment]
Please provide more info if you want this to be fixed. :)
